### ISSUE TITLE
Using github Project instead of github Issues?

### ISSUE THREAD

**Issue by ousamabenyounes** [kanboard/plugin-github-frontend#1]
I'm a great fan of kanboard application...
Happy to see that you're synchronizing kanboard with github issues..
It would be nice to synchronise github project with your plugin?
So when task is done on github it will synchronise it automatically? :)
And if i define the task as done on kanboard, it will automatically set it to done on github project 

what do you think about this?

Thank you again for this really great work!

**Comment by fguillot** [comment]
This is not really the goal of this plugin.
